version: '3.7'

services:
  web:
    build:
      context: ./app
    command: python app.py
    expose:
      - "5000"
    volumes:
      - ./app/:/usr/local/src
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web